### ISSUE TITLE
Multiple mu Variables

### ISSUE THREAD

**Issue by tcoulvert** [quantummind/qaml-z#4]
This for loop here is confusing to me:
https://github.com/quantummind/qaml-z/blob/ab56ddd11606cbcbbc15ca120fcf05c07394cb71/quantum-annealing.py#L312

The variable mu is defined above as this:
https://github.com/quantummind/qaml-z/blob/ab56ddd11606cbcbbc15ca120fcf05c07394cb71/quantum-annealing.py#L295
https://github.com/quantummind/qaml-z/blob/ab56ddd11606cbcbbc15ca120fcf05c07394cb71/quantum-annealing.py#L297

And mus is defined as this:
https://github.com/quantummind/qaml-z/blob/ab56ddd11606cbcbbc15ca120fcf05c07394cb71/quantum-annealing.py#L306

So technically, the for loop is shadowing "mu" with an array equivalent to it? (another 252-length array of zeros) However this for loop is looping over "mus" which is a one element array, why is it doing that? And why are we shadowing "mu" with itself? Since mu is changed in the anneal function calls, are the "mu" references later in that for loop supposed to be the unchanged, original "mu"? Or are they the local "mu" of the for loop, that gets changed in the anneal function?

**Comment by quantummind** [comment]
The `mu0` variable is indeed a remnant that is no longer needed, although it doesn't impact the code's output. Feel free to remove it in your updated version!

While `mus` starts with only one element, it gets overwritten by `new_mus` in Line 333. As seen in https://github.com/quantummind/qaml-z/blob/ab56ddd11606cbcbbc15ca120fcf05c07394cb71/quantum-annealing.py#L331
the variable `new_mus` is longer than one element due to excited states. Hence, `mus` will eventually include more than one element, making the for loop necessary.
